//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMangment.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Status = new HashSet<Status>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int phone { get; set; }
        public string username { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isActive { get; set; }

        public string Password { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Status { get; set; }
        public virtual string numuser { get { return name + " - " + username; } }
        
        public virtual string rePassword { get; set; }
        public virtual string CrPassword { get; set; }
    }
}
